const IMAGE = {
  homeIcon: require('../../assets/Images/homeIconBottom.png'),
  cartIcon: require('../../assets/Images/cartIconBottom.png'),
  favouriteIcon: require('../../assets/Images/favouriteIconBottom.png'),
  orderIcon: require('../../assets/Images/orderIconBottom.png'),
  headerIcon: require('../../assets/Images/headerIcon.png'),
  headerProfile: require('../../assets/Images/headerProfileIcon.png'),
  cappuccinoImg: require('../../assets/Images/cappuccinoImg.png'),
  cartCappuccino: require('../../assets/Images/cartCappuccino.png'),
  robustaBeans: require('../../assets/Images/robustaBeans.png'),
  libericaBeans: require('../../assets/Images/libericaBeans.png'),
  cartMediumTextImg: require('../../assets/Images/cartMediumTextImg.png'),
  cartSImg: require('../../assets/Images/cartSImg.png'),
  cartMImg: require('../../assets/Images/cartMImg.png'),
  cartLImg: require('../../assets/Images/cartLImg.png'),
  leftArrow: require('../../assets/Images/leftArrow.png'),
  favouriteCappuccino: require('../../assets/Images/favouriteCappuccino.png'),
  starImg: require('../../assets/Images/star.png'),
  favouriteCoffeeLogo: require('../../assets/Images/favouriteCoffeeLogo.png'),
  favouriteMilkDrop: require('../../assets/Images/favouriteMilkDrop.png'),
  heart: require('../../assets/Images/heart.png'),
  // macchiatoImg: require('../../ assets/Images/macchiatoImg.png'),
  macchiatoImg: require('../../assets/Images/macchiatoImg.png'),
  macchiatoDetailImg: require('../../assets/Images/macchiatoDetailImg.png'),
  blackCoffeeImg: require('../../assets/Images/blackCoffeeImg.png'),
  blackCoffeeDetailImg: require('../../assets/Images/blackCoffeeDetailImg.png'),
  latteImg: require('../../assets/Images/latteImg.png'),
  latteDetailImg: require('../../assets/Images/latteDetailImg.png'),
  americanoImg: require('../../assets/Images/americanoImg.png'),
  americanoDetailImg: require('../../assets/Images/americanoDetailImg.png'),
  espresso: require('../../assets/Images/espresso.png'),
  espressoDetailImg: require('../../assets/Images/espressoDetailImg.png'),
  robustaBeansDetail: require('../../assets/Images/robustaBeansDetail.png'),
  beansImg: require('../../assets/Images/beansImg.png'),
  excelsaBeansDetail: require('../../assets/Images/excelsaBeansDetail.png'),
  libericaBeansDetail: require('../../assets/Images/libericaBeansDetail.png'),
  libericaBeans: require('../../assets/Images/libericaBeans.png'),
  excelsaBeansImg: require('../../assets/Images/excelsaBeansImg.png'),
  calender: require('../../assets/Images/calender.png'),
  forwardArrow: require('../../assets/Images/forwardArrow.png'),
  light: require('../../assets/Images/light.png'),
  order: require('../../assets/Images/order.png'),
  logOutIcon: require('../../assets/Images/logOutIcon.png'),
  chipImg: require('../../assets/Images/chipImg.png'),
  walletPaymentImg: require('../../assets/Images/walletPaymentImg.png'),
};

export default IMAGE;
