import IMAGE from '../theme/Image';
const BeansData = [
  {
    id: 1,
    backgroundImage: IMAGE.beansImg,
    name: 'Robusta Beans',
    variety: 'Medium Roasted ',
    cost: '$ 4.20',

    button: '+',
    imgStar: IMAGE.starImg,
    bgImg: IMAGE.robustaBeansDetail,
    coffeeFavouriteLogo: IMAGE.favouriteCoffeeLogo,
    coffeeLogoText: 'Coffee',
    milkDrop: IMAGE.favouriteMilkDrop,
    milkText: 'Milk',
    ratingCode: '(6,879)',
    heart: IMAGE.heart,
    quality: 'Medium Roasted',
    des: 'Description',
    desPara:
      'Cappuccino is a latte made with more foam than steamed milk, often with a sprinkle of cocoa powder or cinnamon on top.',
    quantityOne: '250gm',
    quantityThree: '1Kg',
    quantityTwo: '500gm',
  },
  {
    id: 2,
    backgroundImage: IMAGE.beansImg,
    name: 'Robusta Beans',
    variety: 'Medium Roasted ',
    cost: '$ 4.20',

    button: '+',
    imgStar: IMAGE.starImg,
    bgImg: IMAGE.excelsaBeansDetail,
    coffeeFavouriteLogo: IMAGE.favouriteCoffeeLogo,
    coffeeLogoText: 'Coffee',
    milkDrop: IMAGE.favouriteMilkDrop,
    milkText: 'Milk',
    ratingCode: '(6,879)',
    heart: IMAGE.heart,
    quality: 'Medium Roasted',
    des: 'Description',
    desPara:
      'Cappuccino is a latte made with more foam than steamed milk, often with a sprinkle of cocoa powder or cinnamon on top.',
    quantityOne: '250gm',
    quantityThree: '1Kg',
    quantityTwo: '500gm',
  },
  {
    id: 3,
    backgroundImage: IMAGE.excelsaBeansImg,
    name: 'Excelsa Beans',
    variety: 'Medium Roasted ',
    cost: '$ 4.20',

    button: '+',
    imgStar: IMAGE.starImg,
    bgImg: IMAGE.excelsaBeansDetail,
    coffeeFavouriteLogo: IMAGE.favouriteCoffeeLogo,
    coffeeLogoText: 'Coffee',
    milkDrop: IMAGE.favouriteMilkDrop,
    milkText: 'Milk',
    ratingCode: '(6,879)',
    heart: IMAGE.heart,
    quality: 'Medium Roasted',
    des: 'Description',
    desPara:
      'Cappuccino is a latte made with more foam than steamed milk, often with a sprinkle of cocoa powder or cinnamon on top.',
    quantityOne: '250gm',
    quantityThree: '1Kg',
    quantityTwo: '500gm',
  },
  {
    id: 4,
    backgroundImage: require('../assets/Images/beansImg.png'),
    name: 'Robusta Beans',
    variety: 'Medium Roasted ',
    cost: '$ 4.20',

    button: '+',
    imgStar: IMAGE.starImg,
    bgImg: IMAGE.robustaBeansDetail,
    coffeeFavouriteLogo: IMAGE.favouriteCoffeeLogo,
    coffeeLogoText: 'Coffee',
    milkDrop: IMAGE.favouriteMilkDrop,
    milkText: 'Milk',
    ratingCode: '(6,879)',
    heart: IMAGE.heart,
    quality: 'Medium Roasted',
    des: 'Description',
    desPara:
      'Cappuccino is a latte made with more foam than steamed milk, often with a sprinkle of cocoa powder or cinnamon on top.',
    quantityOne: '250gm',
    quantityThree: '1Kg',
    quantityTwo: '500gm',
  },
  {
    id: 5,
    backgroundImage: IMAGE.libericaBeans,
    name: 'Liberica Beans',
    variety: 'Medium Roasted ',
    cost: '$ 4.20',

    button: '+',
    imgStar: IMAGE.starImg,
    bgImg: IMAGE.libericaBeansDetail,
    coffeeFavouriteLogo: IMAGE.favouriteCoffeeLogo,
    coffeeLogoText: 'Coffee',
    milkDrop: IMAGE.favouriteMilkDrop,
    milkText: 'Milk',
    ratingCode: '(6,879)',
    heart: IMAGE.heart,
    quality: 'Medium Roasted',
    des: 'Description',
    desPara:
      'Cappuccino is a latte made with more foam than steamed milk, often with a sprinkle of cocoa powder or cinnamon on top.',
    quantityOne: '250gm',
    quantityThree: '1Kg',
    quantityTwo: '500gm',
  },
  {
    id: 6,
    backgroundImage: require('../assets/Images/beansImg.png'),
    name: 'Robusta Beans',
    variety: 'Medium Roasted ',
    cost: '$ 4.20',

    button: '+',
    imgStar: IMAGE.starImg,
    bgImg: IMAGE.robustaBeansDetail,
    coffeeFavouriteLogo: IMAGE.favouriteCoffeeLogo,
    coffeeLogoText: 'Coffee',
    milkDrop: IMAGE.favouriteMilkDrop,
    milkText: 'Milk',
    ratingCode: '(6,879)',
    heart: IMAGE.heart,
    quality: 'Medium Roasted',
    des: 'Description',
    desPara:
      'Cappuccino is a latte made with more foam than steamed milk, often with a sprinkle of cocoa powder or cinnamon on top.',
    quantityOne: '250gm',
    quantityThree: '1Kg',
    quantityTwo: '500gm',
  },
  {
    id: 7,
    backgroundImage: require('../assets/Images/beansImg.png'),
    name: 'Robusta Beans',
    variety: 'Medium Roasted ',
    cost: '$ 4.20',

    button: '+',
    imgStar: IMAGE.starImg,
    bgImg: IMAGE.libericaBeansDetail,
    coffeeFavouriteLogo: IMAGE.favouriteCoffeeLogo,
    coffeeLogoText: 'Coffee',
    milkDrop: IMAGE.favouriteMilkDrop,
    milkText: 'Milk',
    ratingCode: '(6,879)',
    heart: IMAGE.heart,
    quality: 'Medium Roasted',
    des: 'Description',
    desPara:
      'Cappuccino is a latte made with more foam than steamed milk, often with a sprinkle of cocoa powder or cinnamon on top.',
    quantityOne: '250gm',
    quantityThree: '1Kg',
    quantityTwo: '500gm',
  },
];
export default BeansData;
