import {quantity} from '../store/CounterReducer';
import IMAGE from '../theme/Image';
const HomeData = [
  {
    id: '1',
    backgroundImage: IMAGE.cappuccinoImg,
    name: 'Cappuccino',
    variety: 'With Steamed Milk ',
    cost: 4.2,
    imageStar: require('../assets/Images/star.png'),
    ratingText: '4.5',
    button: '+',
    bgImg: IMAGE.favouriteCappuccino,
    imgStar: IMAGE.starImg,
    coffeeFavouriteLogo: IMAGE.favouriteCoffeeLogo,
    coffeeLogoText: 'Coffee',
    milkDrop: IMAGE.favouriteMilkDrop,
    milkText: 'Milk',
    ratingCode: '(6,879)',
    heart: IMAGE.heart,
    quality: 'Medium Roasted',
    des: 'Description',
    desPara:
      'Cappuccino is a latte made with more foam than steamed milk, often with a sprinkle of cocoa powder or cinnamon on top.',

    Image: IMAGE.cappuccinoImg,
    buttonOne: '+',
    buttonTwo: '-',
    quantityOne: 'S',
    quantityTwo: 'M',
    quantityThree: 'L',
    quantity: 1,
  },
  {
    id: '2',
    backgroundImage: IMAGE.macchiatoImg,
    name: 'Macchiato',
    variety: 'With Foam ',
    cost: 10.2,
    imageStar: require('../assets/Images/star.png'),
    ratingText: '4.5',
    button: '+',
    imgStar: IMAGE.starImg,
    bgImg: IMAGE.macchiatoDetailImg,
    coffeeFavouriteLogo: IMAGE.favouriteCoffeeLogo,
    coffeeLogoText: 'Coffee',
    milkDrop: IMAGE.favouriteMilkDrop,
    milkText: 'Milk',
    ratingCode: '(6,879)',
    heart: IMAGE.heart,
    quality: 'Medium Roasted',
    des: 'Description',
    desPara:
      'Cappuccino is a latte made with more foam than steamed milk, often with a sprinkle of cocoa powder or cinnamon on top.',

    Image: IMAGE.cappuccinoImg,
    buttonOne: '+',
    buttonTwo: '-',
    quantityOne: 'S',
    quantityTwo: 'M',
    quantityThree: 'L',
    quantity: 1,
  },
  {
    id: '3',
    backgroundImage: IMAGE.blackCoffeeImg,
    name: 'Black Coffee',
    variety: 'With Steamed Milk ',
    cost: 5.2,
    imageStar: require('../assets/Images/star.png'),
    ratingText: '4.5',
    button: '+',
    imgStar: IMAGE.starImg,
    bgImg: IMAGE.blackCoffeeDetailImg,
    coffeeFavouriteLogo: IMAGE.favouriteCoffeeLogo,
    coffeeLogoText: 'Coffee',
    milkDrop: IMAGE.favouriteMilkDrop,
    milkText: 'Milk',
    ratingCode: '(6,879)',
    heart: IMAGE.heart,
    quality: 'Medium Roasted',
    des: 'Description',
    desPara:
      'Cappuccino is a latte made with more foam than steamed milk, often with a sprinkle of cocoa powder or cinnamon on top.',

    Image: IMAGE.cappuccinoImg,
    buttonOne: '+',
    buttonTwo: '-',
    quantityOne: 'S',
    quantityTwo: 'M',
    quantityThree: 'L',
    quantity: 1,
  },
  {
    id: '4',
    backgroundImage: IMAGE.latteImg,
    name: 'Latte',
    variety: 'With Steamed Milk ',
    cost: 8.2,
    imageStar: require('../assets/Images/star.png'),
    ratingText: '4.5',
    button: '+',
    imgStar: IMAGE.starImg,
    bgImg: IMAGE.latteDetailImg,
    coffeeFavouriteLogo: IMAGE.favouriteCoffeeLogo,
    coffeeLogoText: 'Coffee',
    milkDrop: IMAGE.favouriteMilkDrop,
    milkText: 'Milk',
    ratingCode: '(6,879)',
    heart: IMAGE.heart,
    quality: 'Medium Roasted',
    des: 'Description',
    desPara:
      'Cappuccino is a latte made with more foam than steamed milk, often with a sprinkle of cocoa powder or cinnamon on top.',

    Image: IMAGE.cappuccinoImg,
    buttonOne: '+',
    buttonTwo: '-',
    quantityOne: 'S',
    quantityTwo: 'M',
    quantityThree: 'L',
    quantity: 1,
  },
  {
    id: '5',
    backgroundImage: IMAGE.americanoImg,
    name: 'Americano',
    variety: 'With Steamed Milk ',
    cost: 9.2,
    imageStar: require('../assets/Images/star.png'),
    ratingText: '4.5',
    button: '+',
    imgStar: IMAGE.starImg,
    bgImg: IMAGE.americanoDetailImg,
    coffeeFavouriteLogo: IMAGE.favouriteCoffeeLogo,
    coffeeLogoText: 'Coffee',
    milkDrop: IMAGE.favouriteMilkDrop,
    milkText: 'Milk',
    ratingCode: '(6,879)',
    heart: IMAGE.heart,
    quality: 'Medium Roasted',
    des: 'Description',
    desPara:
      'Cappuccino is a latte made with more foam than steamed milk, often with a sprinkle of cocoa powder or cinnamon on top.',

    Image: IMAGE.cappuccinoImg,
    buttonOne: '+',
    buttonTwo: '-',
    quantityOne: 'S',
    quantityTwo: 'M',
    quantityThree: 'L',
    quantity: 1,
  },
  {
    id: '6',
    backgroundImage: IMAGE.cappuccinoImg,
    name: 'Cappuccino',
    variety: 'With Steamed Milk ',
    cost: 6.9,
    imageStar: require('../assets/Images/star.png'),
    ratingText: '4.5',
    button: '+',
    imgStar: IMAGE.starImg,
    bgImg: IMAGE.favouriteCappuccino,
    coffeeFavouriteLogo: IMAGE.favouriteCoffeeLogo,
    coffeeLogoText: 'Coffee',
    milkDrop: IMAGE.favouriteMilkDrop,
    milkText: 'Milk',
    ratingCode: '(6,879)',
    heart: IMAGE.heart,
    quality: 'Medium Roasted',
    des: 'Description',
    desPara:
      'Cappuccino is a latte made with more foam than steamed milk, often with a sprinkle of cocoa powder or cinnamon on top.',

    Image: IMAGE.cappuccinoImg,
    buttonOne: '+',
    buttonTwo: '-',
    quantityOne: 'S',
    quantityTwo: 'M',
    quantityThree: 'L',
    quantity: 1,
  },
  {
    id: '7',
    backgroundImage: IMAGE.cappuccinoImg,
    name: 'Cappuccino',
    variety: 'With Steamed Milk ',
    cost: 6.9,
    imageStar: require('../assets/Images/star.png'),
    ratingText: '4.5',
    button: '+',
    imgStar: IMAGE.starImg,
    bgImg: IMAGE.favouriteCappuccino,
    coffeeFavouriteLogo: IMAGE.favouriteCoffeeLogo,
    coffeeLogoText: 'Coffee',
    milkDrop: IMAGE.favouriteMilkDrop,
    milkText: 'Milk',
    ratingCode: '(6,879)',
    heart: IMAGE.heart,
    quality: 'Medium Roasted',
    des: 'Description',
    desPara:
      'Cappuccino is a latte made with more foam than steamed milk, often with a sprinkle of cocoa powder or cinnamon on top.',

    Image: IMAGE.cappuccinoImg,
    buttonOne: '+',
    buttonTwo: '-',
    quantityOne: 'S',
    quantityTwo: 'M',
    quantityThree: 'L',
    quantity: 1,
  },
  {
    id: '8',
    backgroundImage: IMAGE.espresso,
    name: 'Espresso',
    variety: 'With Steamed Milk ',
    cost: 3.2,
    imageStar: require('../assets/Images/star.png'),
    ratingText: '4.5',
    button: '+',
    imgStar: IMAGE.starImg,
    bgImg: IMAGE.espressoDetailImg,
    coffeeFavouriteLogo: IMAGE.favouriteCoffeeLogo,
    coffeeLogoText: 'Coffee',
    milkDrop: IMAGE.favouriteMilkDrop,
    milkText: 'Milk',
    ratingCode: '(6,879)',
    heart: IMAGE.heart,
    quality: 'Medium Roasted',
    des: 'Description',
    desPara:
      'Cappuccino is a latte made with more foam than steamed milk, often with a sprinkle of cocoa powder or cinnamon on top.',

    Image: IMAGE.cappuccinoImg,
    buttonOne: '+',
    buttonTwo: '-',
    quantityOne: 'S',
    quantityTwo: 'M',
    quantityThree: 'L',
    quantity: 1,
  },
  {
    id: '9',
    backgroundImage: IMAGE.espresso,
    name: 'Espresso',
    variety: 'With Steamed Milk ',
    cost: 4.2,
    imageStar: require('../assets/Images/star.png'),
    ratingText: '4.5',
    button: '+',
    imgStar: IMAGE.starImg,
    bgImg: IMAGE.espressoDetailImg,
    coffeeFavouriteLogo: IMAGE.favouriteCoffeeLogo,
    coffeeLogoText: 'Coffee',
    milkDrop: IMAGE.favouriteMilkDrop,
    milkText: 'Milk',
    ratingCode: '(6,879)',
    heart: IMAGE.heart,
    quality: 'Medium Roasted',
    des: 'Description',
    desPara:
      'Cappuccino is a latte made with more foam than steamed milk, often with a sprinkle of cocoa powder or cinnamon on top.',

    Image: IMAGE.cappuccinoImg,
    buttonOne: '+',
    buttonTwo: '-',
    quantityOne: 'S',
    quantityTwo: 'M',
    quantityThree: 'L',
    quantity: 1,
  },
  {
    id: '10',
    backgroundImage: IMAGE.americanoImg,
    name: 'Americano',
    variety: 'With Steamed Milk ',
    cost: 6.9,
    imageStar: require('../assets/Images/star.png'),
    ratingText: '4.5',
    button: '+',
    imgStar: IMAGE.starImg,
    bgImg: IMAGE.americanoDetailImg,
    coffeeFavouriteLogo: IMAGE.favouriteCoffeeLogo,
    coffeeLogoText: 'Coffee',
    milkDrop: IMAGE.favouriteMilkDrop,
    milkText: 'Milk',
    ratingCode: '(6,879)',
    heart: IMAGE.heart,
    quality: 'Medium Roasted',
    des: 'Description',
    desPara:
      'Cappuccino is a latte made with more foam than steamed milk, often with a sprinkle of cocoa powder or cinnamon on top.',

    Image: IMAGE.cappuccinoImg,
    buttonOne: '+',
    buttonTwo: '-',
    quantityOne: 'S',
    quantityTwo: 'M',
    quantityThree: 'L',
    quantity: 1,
  },
];
export default HomeData;
